openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /locations:
    get:
      summary: Returns a list of locations.
      responses:
        "200": # status code
          description: A JSON array of location names and API endpoint URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /locations/{id}:
    get:
      summary: Returns a single location's cached weather data
      responses:
        "200":
          description: A JSON object with a location's name and weather data
          content:
            application/json:
              schema:
                type: object
components:
  {}